### ISSUE TITLE
Environment Support

### ISSUE THREAD

**Issue by megawac** [underdash/underdash#3]
Do we want to continue supporting long dead environments such as 5 year old versions of WebKit and IE6?

If so do we want to have a compatibility build and a modern build as lodash currently does?

**Comment by jashkenas** [comment]
For what it's worth, my employer (http://nytimes.com) just dropped support for IE9 this morning. Which leaves IE11 and up (evergreens) as the only Explorers on the support list.

I'd be fine with any of the following options:

1. Support old browsers because we can.
2. Support old browsers with two build files, a-la jQuery.
3. Drop support for old browsers, because the time is nigh. Folks supporting old browsers can simply use old versions of Underscore in peace.

I'd be fine with any of those, but am most tempted by door # 3. It would be lovely to start fresh in an "evergreen browser" world.

**Comment by jdalton** [comment]
IE9 isn't much of an issue in the context of Underscore but I'm cool with dropping older. I've defaulted to `modern` in lodash. We don't really error in older just lack the bug fixes for iteration and things. It does seem that there's still a demand for compat builds (older enviros) which is why I'm OK having a build for them.

**Comment by jdalton** [comment]
Btw opting ES6 features requires branching too so it's a bit of trading one for the other :P

**Comment by paulfalgout** [comment]
Government and Healthcare will likely be stuck at IE8 for a while.  Official support for Vista is through [April 11, 2017](http://windows.microsoft.com/en-us/windows/lifecycle)  I don't see IE6 or even 7 to really be an issue, but that might not be true internationally.

**Comment by megawac** [comment]
Personally I'm thinking

IE>=7 or 8, Safari>=4, WebKit>3 years, Node>=0.8, FF>?

**Comment by SimenB** [comment]
Healthcare in Norway is also IE8. Whether or not there's a build called `compat` or just the normal one doesn't matter much, but I'd like the support to exist in some way in the new (or base/merged) project.

**Comment by jashkenas** [comment]
Sounds fine. Backwards-compat support for the governments it is.

**Comment by mbrevda** [comment]
@jashkenas Do you mean baked-in "Backwards-compat support", or a `compat` lib?

I question how much projects that are rooted in the past, really care or need the improvements offered in newer versions of libs such as this. They're obviously not concerned about speed/efficiency/security - or they would have rolled out chrome/chromefram. They're obviously not concerned about the latest and greatest - as is evident by their dinosaur age browsers.

There is no reason for the other 95%* of people to load a larger/clunkier/code-smellier lib for the sake of those that are living in past. While I see nothing wrong with them keeping on use the current version until they can "get with the times", I think a `compat` lib would be a great compromise.

*or whatever the number is

**Comment by jdalton** [comment]
Lodash v4 is modern. The current and next to current release of Chrome, Firefox, Safari and & IE >= 9 (We have no IE9 or IE10 fixes so get it for free). With [MS dropping support for IE < 11](https://www.microsoft.com/en-us/WindowsForBusiness/End-of-IE-support) that's a fine bar to set. Those still needing older environment support can supplement with ES5-shim and, optionally, ES6-shim.

**Comment by paulfalgout** [comment]
FWIW I believe Microsoft still supports IE9 through some sort of extended service contract related to Vista through Jan 2017, but IE8 is finally dead.

**Comment by jdalton** [comment]
@paulfalgout

Yes though Vista end-of-lifes next year so it's easier to just say IE < 11.

**Comment by IanYates** [comment]
:+1: 

And those poor unfortunate souls using Windows 2012 server as a remote desktop server (sadly I have to support software on quite a few of these at client sites :sob: ) are isolated on IE 10 and it's supported for quite a while as there was no free upgrade to server 2012 R2. 

In the real world there shouldn't be very many of these since there was perhaps 18 months at most between the release of the two OSes and most IT shops tend to see the "R2" releases as big service packs.  Those people stuck on Windows 8 - not moving to 8.1 - should be even more rare I'd hope!

However IE 10 is not all that different from IE 11 and, should there be trouble, I'm personally happy to tell them to run Chrome on the remote desktop server for our software.

**Comment by jdalton** [comment]
We have no IE 9-10 specific fixes. Folks can enable old browser support using es5-shim, and optionally es6-shim.

**Comment by jdalton** [comment]
Closed by #14.
